### ISSUE TITLE
Docker broken

### ISSUE THREAD

**Issue by abretaud** [askomics/askomics#168]
```
Attaching to virtuoso_askomics_1
askomics_1  |  === use config base : ./configs/custom.ini 
askomics_1  | Custom triplestore endpoint: http://virtuoso:8890/sparql
askomics_1  | Defined triplestore auth with username dba
askomics_1  | Custom load url: http://askomics:6543
askomics_1  | -- SMTP definition --
askomics_1  | deploying javascript ...
askomics_1  | starting askomics ...
askomics_1  | python3 -s -bb -Wall ./venv/bin/pserve ./configs/custom.ini --reload
askomics_1  | module.js:328
askomics_1  |     throw err;
askomics_1  |     ^
askomics_1  | Error: Cannot find module 'pump'
askomics_1  |     at Function.Module._resolveFilename (module.js:326:15)
askomics_1  |     at Function.Module._load (module.js:277:25)
askomics_1  |     at Module.require (module.js:354:17)
askomics_1  |     at require (internal/module.js:12:17)
askomics_1  |     at Object.<anonymous> (/usr/local/askomics/gulpfile.js:19:12)
askomics_1  |     at Module._compile (module.js:410:26)
askomics_1  |     at Object.Module._extensions..js (module.js:417:10)
askomics_1  |     at Module.load (module.js:344:32)
askomics_1  |     at Function.Module._load (module.js:301:12)
askomics_1  |     at Module.require (module.js:354:17)
askomics_1  |     at require (internal/module.js:12:17)
askomics_1  |     at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
askomics_1  |     at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:198:16)
askomics_1  |     at module.exports (/usr/local/lib/node_modules/gulp/node_modules/flagged-respawn/index.js:17:3)
askomics_1  |     at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:190:9)
askomics_1  |     at /usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:164:9

```

I get this when launching a brand new askomics instance after a docker-compose pull
@xgaia are you guilty??

**Comment by xgaia** [comment]
my fault sorry. I fixed this by adding the missing package in `package.json`. @ofilangi can you rebuild the docker ?

**Comment by ofilangi** [comment]
in progress...

**Comment by abretaud** [comment]
It seems to work no,w but I get this in the logs:

```
askomics_1  | [12:29:31] Error: watch /usr/local/askomics/askomics/static/src/js/view/parameters/ ENOSPC
askomics_1  |     at exports._errnoException (util.js:870:11)
askomics_1  |     at FSWatcher.start (fs.js:1234:19)
askomics_1  |     at Object.fs.watch (fs.js:1262:11)
askomics_1  |     at Gaze._watchDir (/usr/local/askomics/node_modules/gaze/lib/gaze.js:289:30)
askomics_1  |     at /usr/local/askomics/node_modules/gaze/lib/gaze.js:358:10
askomics_1  |     at iterate (/usr/local/askomics/node_modules/gaze/lib/helper.js:52:5)
askomics_1  |     at /usr/local/askomics/node_modules/gaze/lib/helper.js:61:11
askomics_1  |     at /usr/local/askomics/node_modules/gaze/lib/gaze.js:420:5
askomics_1  |     at iterate (/usr/local/askomics/node_modules/gaze/lib/helper.js:52:5)
askomics_1  |     at /usr/local/askomics/node_modules/gaze/lib/helper.js:61:11
askomics_1  |     at /usr/local/askomics/node_modules/gaze/lib/gaze.js:420:5
askomics_1  |     at iterate (/usr/local/askomics/node_modules/gaze/lib/helper.js:52:5)
askomics_1  |     at /usr/local/askomics/node_modules/gaze/lib/helper.js:61:11
askomics_1  |     at /usr/local/askomics/node_modules/gaze/lib/gaze.js:420:5
askomics_1  |     at iterate (/usr/local/askomics/node_modules/gaze/lib/helper.js:52:5)
askomics_1  |     at /usr/local/askomics/node_modules/gaze/lib/helper.js:61:11
```

Don't know if it's bad or not

**Comment by ofilangi** [comment]
12:29:31.....there are a new image since...could you pull askomics again and retry ?
