### ISSUE TITLE
Problem for identification

### ISSUE THREAD

**Issue by mwery** [askomics/askomics#268]
Hi, 

When I want to connect on my askomics account, I've got this log message : 

http://localhost:6543/_debug_toolbar/313339383635303037373739303634/exception

```
Traceback (most recent call last):
  File "/home/mwery/Documents/Software/askomics/venv/lib/python3.6/site-packages/pyramid/tweens.py", line 12, in _error_handler
    response = request.invoke_exception_view(exc_info)
  File "/home/mwery/Documents/Software/askomics/venv/lib/python3.6/site-packages/pyramid/view.py", line 731, in invoke_exception_view
    raise HTTPNotFound
pyramid.httpexceptions.HTTPNotFound: The resource could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mwery/Documents/Software/askomics/venv/lib/python3.6/site-packages/waitress/channel.py", line 338, in service
    task.service()
  File "/home/mwery/Documents/Software/askomics/venv/lib/python3.6/site-packages/waitress/task.py", line 169, in service
    self.execute()
  File "/home/mwery/Documents/Software/askomics/venv/lib/python3.6/site-packages/waitress/task.py", line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/home/mwery/Documents/Software/askomics/venv/lib/python3.6/site-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/home/mwery/Documents/Software/askomics/venv/lib/python3.6/site-packages/pyramid/router.py", line 278, in default_execution_policy
    return request.invoke_exception_view(reraise=True)
  File "/home/mwery/Documents/Software/askomics/venv/lib/python3.6/site-packages/pyramid/view.py", line 730, in invoke_exception_view
    reraise_(*exc_info)
  File "/home/mwery/Documents/Software/askomics/venv/lib/python3.6/site-packages/pyramid/compat.py", line 148, in reraise
    raise value
  File "/home/mwery/Documents/Software/askomics/venv/lib/python3.6/site-packages/pyramid/router.py", line 276, in default_execution_policy
    return router.invoke_request(request)
  File "/home/mwery/Documents/Software/askomics/venv/lib/python3.6/site-packages/pyramid/router.py", line 249, in invoke_request
    response = handle_request(request)
  File "/home/mwery/Documents/Software/askomics/venv/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = _error_handler(request, exc)
  File "/home/mwery/Documents/Software/askomics/venv/lib/python3.6/site-packages/pyramid/tweens.py", line 16, in _error_handler
    reraise(*exc_info)
  File "/home/mwery/Documents/Software/askomics/venv/lib/python3.6/site-packages/pyramid/compat.py", line 148, in reraise
    raise value
  File "/home/mwery/Documents/Software/askomics/venv/lib/python3.6/site-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/home/mwery/Documents/Software/askomics/venv/lib/python3.6/site-packages/pyramid/router.py", line 156, in handle_request
    view_name
  File "/home/mwery/Documents/Software/askomics/venv/lib/python3.6/site-packages/pyramid/view.py", line 617, in _call_view
    response = view_callable(context, request)
  File "/home/mwery/Documents/Software/askomics/venv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/mwery/Documents/Software/askomics/venv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/mwery/Documents/Software/askomics/venv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/mwery/Documents/Software/askomics/venv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 123, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/home/mwery/Documents/Software/askomics/askomics/ask_view.py", line 1296, in login
    password_is_correct = security.check_email_password()
  File "/home/mwery/Documents/Software/askomics/askomics/libaskomics/Security.py", line 118, in check_email_password
    ts_salt = result[0]['salt']
IndexError: list index out of range
```

Thanks, 
Méline

**Comment by abretaud** [comment]
¡Ola!
Yo pienso que este buggo esta corrigado con la pulla requesta #269. ¿Puedes git pullar y relançar tu askomics?
I think this error showed up because you use a recent askomics with old data in the virtuoso server. With a fresh install I *think* you wouldn't have it (at least I didn't in my tests).
Cordialement bien à vous
