### ISSUE TITLE
Integating data

### ISSUE THREAD

**Issue by mwery** [askomics/askomics#270]
Hi, 

I've got this error message : 

```
2018-06-06 11:09:08,623 ERROR [pyramid_debugtoolbar][waitress] Uncaught sqlite3.OperationalError at http://localhost:6543/load_data_into_graph
traceback url: http://localhost:6543/_debug_toolbar/313339393633393138363937373532/exception
Traceback (most recent call last):
  File "/home/mwery/Documents/Software/askomics/venv/lib/python3.6/site-packages/pyramid/tweens.py", line 12, in _error_handler
    response = request.invoke_exception_view(exc_info)
  File "/home/mwery/Documents/Software/askomics/venv/lib/python3.6/site-packages/pyramid/view.py", line 731, in invoke_exception_view
    raise HTTPNotFound
pyramid.httpexceptions.HTTPNotFound: The resource could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mwery/Documents/Software/askomics/venv/lib/python3.6/site-packages/pyramid_debugtoolbar/toolbar.py", line 248, in toolbar_tween
    response = _handler(request)
  File "/home/mwery/Documents/Software/askomics/venv/lib/python3.6/site-packages/pyramid_debugtoolbar/panels/performance.py", line 58, in resource_timer_handler
    result = handler(request)
  File "/home/mwery/Documents/Software/askomics/venv/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = _error_handler(request, exc)
  File "/home/mwery/Documents/Software/askomics/venv/lib/python3.6/site-packages/pyramid/tweens.py", line 16, in _error_handler
    reraise(*exc_info)
  File "/home/mwery/Documents/Software/askomics/venv/lib/python3.6/site-packages/pyramid/compat.py", line 148, in reraise
    raise value
  File "/home/mwery/Documents/Software/askomics/venv/lib/python3.6/site-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/home/mwery/Documents/Software/askomics/venv/lib/python3.6/site-packages/pyramid/router.py", line 156, in handle_request
    view_name
  File "/home/mwery/Documents/Software/askomics/venv/lib/python3.6/site-packages/pyramid/view.py", line 617, in _call_view
    response = view_callable(context, request)
  File "/home/mwery/Documents/Software/askomics/venv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/mwery/Documents/Software/askomics/venv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/mwery/Documents/Software/askomics/venv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/mwery/Documents/Software/askomics/venv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 123, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/home/mwery/Documents/Software/askomics/askomics/ask_view.py", line 662, in load_data_into_graph
    jobid = jm.saveStartSparqlJob(file_name)
  File "/home/mwery/Documents/Software/askomics/askomics/libaskomics/JobManager.py", line 62, in saveStartSparqlJob
    c.execute(reqSql)
sqlite3.OperationalError: table jobs has 10 columns but 11 values were supplied

```

**Comment by abretaud** [comment]
Oh, the problem is that there is a small sqlite database in your installation that is no more compatible with latest version...
Do you have a file named jobs.db in /tmp/askomics/db/ ? If yes, try removing it
